### ISSUE TITLE
Add Checksum

### ISSUE THREAD

**Issue by shrimprugbysnowowl** [oxen-io/lokinet-flutter-app#13]
Consider adding a checksum so users can verify the integrity of the downloaded/built apk.

Thanks for all your effort on the android version, everyone!  Much appreciated, and very excited to see it hit f-droid eventually.

**Comment by majestrate** [comment]
we can supplement with hashes in a signed file but hashes can be modified in transit too if someone wants to be malicious.
it makes more sense to me to just make signed release builds if you are looking for security integrity.

**Comment by shrimprugbysnowowl** [comment]
Agreed
