### ISSUE TITLE
Unable to set 127.0.0.1 as upstream DNS.

### ISSUE THREAD

**Issue by bialy39** [oxen-io/lokinet-flutter-app#14]
I have instance of dnscrypt-proxy listening on 127.0.0.1 and i would use is as DNS.

Lokinet app is throwing an error:
...
java.lang.RuntimeException: Unable to start service network.loki.lokinet.LokinetDaemon@2778f11 with Intent { act=network.loki.lokinet.START cmp=io.oxen.lokinet/network.loki.lokinet.LokinetDaemon (has extras) }: java.lang.IllegalArgumentException: Bad address
...
java.lang.IllegalArgumentException: Bad address

**Comment by majestrate** [comment]
the way android lokinet does dns right now is a bit jenk. we require dns to be not a "bogon ip" so the os is forced to shove it over the vpn interface where we (at layer 3) dynamically intercept udp 53 and consume dns queries for .loki and .snode and pass them thru if not. if you got dnscrypt proxy already you can add forwarding to .loki and .snode from it and have dnscrypt proxy own dns, this needs to be implement in android still. how did you get dnscrypt proxy to run? i would like to ship this cinfiguration if i can do it rootless as it is objectively better than what we have now.

**Comment by bialy39** [comment]
Unfortunately phone is rooted by Magisk and I use dnscrypt-proxy as magisk module.

**Comment by majestrate** [comment]
ah okay, you may have better luck with the debian packages if you can run as root, via a chroot.
