### ISSUE TITLE
Unable to access any websites

### ISSUE THREAD

**Issue by jschenke488** [oxen-io/lokinet-flutter-app#15]
The app says connected, but I'm unable to access any websites. Here's the log from logcat, these same lines are spammed many times (I'm using Shizuku with Termux to read the logs)
![Screenshot_20220826-003412_Termux](https://user-images.githubusercontent.com/44783760/186830458-ac42b34b-79ed-495b-9da2-2de271f4475a.jpg)

**Comment by majestrate** [comment]
can you post:

* git revisions for the flutter repo and the lokinet submodule
* flutter version
* android version
* hardware specs

**Comment by jschenke488** [comment]
> can you post:
> 
> * git revisions for the flutter repo and the lokinet submodule
> * flutter version
> * android version
> * hardware specs

https://oxen.rocks/oxen-io/lokinet/stable/lokinet-android-v0.9.9.apk
android 12
samsung galaxy s21 fe 5g (snapdragon arm64-v8a model if I remember correctly?)

**Comment by majestrate** [comment]
the apk from the 0.9.9 tag is known to be broken, use 0.9.8 
the android builds are technically undisclosed and not publically supported as a target at this time so regressions may and probably will happen until an official public release is put out.
