### ISSUE TITLE
`liblokinet-android.so` not found in dev build

### ISSUE THREAD

**Issue by 0x330a** [oxen-io/lokinet-flutter-app#17]
the `lokinet_lib` android build process succeeds but looks in the wrong place for the artifacts on the `ensureNativeLibs` task, idk if it's a script in the lokinet submodule that does it (`contrib/android.sh`) or whether it's the currently expected path and just need to update the build.gradle to point to the new location.

Changing `include 'out/*/*.so'` to `include 'lokinet-jni-v0.9.8/*/*.so'` in the `ensureNativeLibs` task seems to fix it. Current behaviour is just a blank splash screen with failing to find the .so files in logcat. Can open a PR if that fix is ok :+1:

**Comment by majestrate** [comment]
revert this commit https://github.com/oxen-io/lokinet-flutter-app/commit/54a416ce7a5d5c4233d0a4af3662c8865f2fc14b

**Comment by ManeraKai** [comment]
I'm not able to build it myself still:
![image](https://github.com/oxen-io/lokinet-flutter-app/assets/40805353/dbad3a0e-7b4d-4822-a68a-387b379e7e8f)

**Comment by majestrate** [comment]
is this being built on windows?

**Comment by ManeraKai** [comment]
No this linux Kubuntu LTS. I tried both VSCode and Android studio but both aren't working.

**Comment by majestrate** [comment]
On Saturday, 20 May 2023 06:16:00 EDT ManeraKai wrote:
> Noon linux Kubuntu LTS. I tried both VsCode and Android studio but both
> aren't working

looks like you need the android NDK installed. if you are using android studio 
you can set ndk.dir setting in local.properties to point to the path it is 
installed or you can install the ndk to the system with apt:

sudo apt install google-android-ndk-installer

the latter method using apt works on debian bookworm. 


which kubuntu lts are you using? last i checked there are 2 versions and one 
of them is way too old.

-- 
~jeff

**Comment by ManeraKai** [comment]
![image](https://github.com/oxen-io/lokinet-flutter-app/assets/40805353/f3cfd80c-2239-4e7c-a346-7ca464a4f25b)
but it's Kubuntu

> sudo apt install google-android-ndk-installer

I'll try it now

**Comment by ManeraKai** [comment]
I installed the latest ndk version (25.2.9519653), but now this is happenning:
![image](https://github.com/oxen-io/lokinet-flutter-app/assets/40805353/93b09c51-663d-4719-8de1-d2150d0b3ba1)
I go and check the file:
![image](https://github.com/oxen-io/lokinet-flutter-app/assets/40805353/0644a4a3-242d-444e-b76b-9788bfd8a196)
This `C compiler cannot create executables` is happening multiple times across the build and it fails.

**Comment by Zardon703** [comment]
> I installed the latest ndk version (25.2.9519653), but now this is happenning: ![image](https://user-images.githubusercontent.com/40805353/239723221-93b09c51-663d-4719-8de1-d2150d0b3ba1.png) I go and check the file: ![image](https://user-images.githubusercontent.com/40805353/239723209-0644a4a3-242d-444e-b76b-9788bfd8a196.png) This `C compiler cannot create executables` is happening multiple times across the build and it fails.

any luck with it?

**Comment by ManeraKai** [comment]
nope.

**Comment by Zardon703** [comment]
> nope.

Maybe trying a different distro may work tbh (Tho I should follow that advice myself XD)

**Comment by 0x330a** [comment]
The original issue I had was fixed in the first comment, I'm going to close this so it doesn't turn into tracking an unrelated issue :+1:

**Comment by Zardon703** [comment]
> The original issue I had was fixed in the first comment, I'm going to close this so it doesn't turn into tracking an unrelated issue 👍

So, i'm guessing you'll push what you found to the devs to help with progress?

**Comment by 0x330a** [comment]
the solution was the first comment by a developer "revert this commit https://github.com/oxen-io/lokinet-flutter-app/commit/54a416ce7a5d5c4233d0a4af3662c8865f2fc14b".
The NDK stuff wasn't related to my issue

**Comment by majestrate** [comment]
On Tuesday, August 15, 2023 3:24:21 AM EDT 0x330a wrote:
> the solution was the first comment by a developer "revert this commit
> https://github.com/oxen-io/lokinet-flutter-app/commit/54a416ce7a5d5c4233d0a
> 4af3662c8865f2fc14b". The NDK stuff wasn't related to my issue

revert to that commit.
it SHOULD work.


-- 
~jeff
