### ISSUE TITLE
Unable to load webpages

### ISSUE THREAD

**Issue by ghost** [oxen-io/lokinet-flutter-app#2]
Install the lokinet app, give permissions, yadayadayada...
1. Try to load probably.loki on Brave chromium and get errors on DNS lookup
2. Set up the dns to the adguard one and have the same issues
3. My phone is too slow to load webpages with any exit node, so someone else should troubleshoot.

Using the debug lokinet app works though...

**Comment by majestrate** [comment]
lokinet dns is required for .loki to resolve.
