### ISSUE TITLE
Incompatiblity with private DNS

### ISSUE THREAD

**Issue by ghost** [oxen-io/lokinet-flutter-app#9]
Android does not resolve .loki addresses when private DNS is enabled

Steps to reproduce:
1. Go to Settings > Network & internet
2. Select Advanced > Private DNS
3. Select the Private DNS provider hostname option
4. Enter a DoT adress (for example `dns.quad9.net`)
5. Open lokinet and enable it
6. Go to a .loki adress (for example `http://probably.loki`)
7. See the error 

Screenshots:

<img src="https://user-images.githubusercontent.com/70704875/156885597-685b43a1-330a-4ee1-b700-af69d88723be.jpg" width="288" height="600" />
<img src="https://user-images.githubusercontent.com/70704875/156885599-0cf0824b-e3f2-4d3d-98cb-f14392ba5565.jpg" width="288" height="600" />
<img src="https://user-images.githubusercontent.com/70704875/156885608-5e047e02-fbb3-4ac4-a485-5b488ed4fb4a.jpg" width="288" height="600" />

**Comment by majestrate** [comment]
lokinet intercepts dns queries locally and forwards them to upstream if they are not for the `.loki` gtld. if you use "secure" dns it bypasses lokinet entirely and we cannot resolve them as the queries go over an encrypted tunnel to quad nine in your case, who isn't providing lokinet.
